name: WebP Pixbuf CI [MacOS]

on:
  push:
    branches:
      - mainline
  pull_request:
    branches:
      - mainline

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies via Homebrew
        run: |
          brew update

          # fix `brew link python@3.12` issue
          # see upstream discussion in https://github.com/actions/setup-python/issues/577

          rm -f /usr/local/bin/2to3
          rm -f /usr/local/bin/idle3
          rm -f /usr/local/bin/pydoc3
          rm -f /usr/local/bin/python3
          rm -f /usr/local/bin/python3-config
          rm -f /usr/local/bin/2to3-3.12
          rm -f /usr/local/bin/idle3.12
          rm -f /usr/local/bin/pydoc3.12
          rm -f /usr/local/bin/python3.12
          rm -f /usr/local/bin/python3.12-config

          brew install webp gdk-pixbuf meson ninja pkg-config

      - run: meson setup build
      - run: meson compile -C build --verbose
      - run: meson test -C build --print-errorlogs
