name: WebP Pixbuf CI [MacOS]

on:
  push:
    branches:
      - mainline
  pull_request:
    branches:
      - mainline

jobs:
  Build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - run: brew update
      - run: brew install webp gdk-pixbuf meson ninja pkg-config
      - run: meson setup build
      - run: meson compile -C build --verbose
      - run: meson test -C build --print-errorlogs
