name: WebP Pixbuf CI [Ubuntu]
'on':
  push:
    branches:
      - mainline
  pull_request:
    branches:
      - mainline
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: sudo apt update
      - run: sudo apt install ninja-build meson libwebp-dev libgdk-pixbuf2.0-dev
      - run: mkdir build
      - run: meson build
      - run: ninja -C build
      - run: meson test -C build --print-errorlogs
      - run: meson -C build scan-build
