name: WebP Pixbuf CI [Ubuntu]

on:
  push:
    branches:
      - mainline
  pull_request:
    branches:
      - mainline

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:noble
    steps:
      - uses: actions/checkout@v4
      - run: apt update
      - run: apt install -y ninja-build meson libwebp-dev libgdk-pixbuf2.0-dev valgrind clang clang-tools
      - run: mkdir build
      - run: meson build
      - run: ninja -C build
      - run: ninja -C build scan-build
      - run: meson test -C build --print-errorlogs
      - run: meson test -C build --wrapper 'valgrind --leak-check=full --error-exitcode=1'
